---
title: " "
output: pdf_document
header-includes:
  - \usepackage{float}
  - \usepackage{sectsty}
---

# Introduction

It is important in sports to gain insight and knowledge of the physical demands from training and matches to improve performance and prevent injuries. Some of the most frequently reported metrics in football are: distance covered, distance in velocity zones and number of acc- & decelerations \citep{Aughey2011}. These metrics are most commonly being measured with the use of Global Positioning Systems (GPS), which have seen an exponentially growth in outdoor team-sports. GPS is validated for use in outdoor team sports with a sampling frequency of minimum 10 Hz \citep{Scott2016, Johnston2014}. Furthermore, \citet{Petersen2009} also found that the reliability of the GPS was independent on the time of day. Nonetheless, these metrics mostly focus on linear movements and does not take into account the load from small and energy demanding non-linear movements like change of directions, jumps or the amplitude of an acceleration or deceleration. These are all relevant aspects for team coaches since it provides more details on the loading of a training session or a game.

Football has over the last decade experienced an increase in the quantity of short bouts of activity, compared to total distance travelled \citep{Barnes2014} and some studies have shown upwards of eightfold more occurrences of accelerations than sprints \citep{Bradley2010, Varley2012}. Accelerations also has a greater metabolic demand than steady state running \citep{Prampero2005, Osgnach2010, Stevens2015}, therefore a huge part of the physical demand is never accounted for with the use of the conventional metrics from GPS data. Thus, it is important for the practitioners to monitor the acc- & decceleration profile of the players. Though, GPS has shown poor validity with accelerations above $4\: m\cdot s^{-2}$ \citep{Akenhead2014}.

Another approach is to use Inertial Measurement Units (IMU), since these are now miniaturized and non obstructive \citep{Zheng2014}. IMUs are experiencing an increase in popularity and have been successfully used in both outdoor and indoor team sports, to measure the physical demands \citep{GomezCarmona2020, Cust2018}. The IMUs in Catapult Sports' tracking device, Minimax S4 and OptimEye S5, has shown to have an acceptable level of validity and reliability \citep{Wundersitz2015, Luteberget2018, Nicolella2018}. 
One of the most commonly used metrics in football from an IMU, is the magnitude of accelerations (square root of the summed squares of the three axis). The magnitude of acceleration is the instantaneous rate of change in acceleration across all three axis. This has been given names like $PlayerLoad^{TM}$ (Catapult Sports) and $Body Load$ (GPSports). Where $PlayerLoad^{TM}$ has shown acceptable reliability during Australian Football matches both within and between the used devices (MinimaxX 2.0, Catapult Sports) \citep{Boyd2011}.

Based on the accelerometer data from the IMU, and therefore also the magnitude of accelerations,
Catapult Sports have developed a sport specific movement algorithm (Football Movement profile (FMP)). The FMP is an attempt to create a deeper insight into the demands of football. The algorithm classify movements in six categories depended on intensity and if it is a linear or a multi directional movement; 

* **Very Low intensity** - Standing-like movements
* **Low intensity** - Walking-like movements
* **Running medium intensity** - Steady jogging / running (linear locomotion)
* **Running high intensity** - Steady high-speed running (linear locomotion)
* **Dynamic medium intensity** - Mid-intensity changes of direction and accelerations (non-linear locomotion)
* **Dynamic high intensity** - High-intensity changes of direction and accelerations (non-linear locomotion)

Henceforward, the running and dynamic categories will be used interchangeable with linear and non-linear locomotion, respectively. **Furthermore, the word *intensity* is used to differentiate between drills and the expectation in internal load. *Load* describes the internal work that is needed to overcome an obstacle. In this study, load will be quantified based on accelerometer data.**

These categories are all derived over 1 sec epochs (1 Hz). By utilizing linear acceleration data from the IMUs, it is possible to get a deeper and more relevant insight into the loading characteristics in players, compared to linear velocity data. Though, it is possible to derive linear acceleration from linear velocity data by calculating its derivative $v(t) = \frac{dr}{dt}$. However, this will affect the white noise of the original signal and therefore the error of the data will be amplified when calculating its derivative which can result in a poor signal to noise ratio \citep{Payton2017}.
Nonetheless, working with acceleration data from IMUs can be cumbersome and the alternative would be to use motion capture analysis, but these are highly time-consuming \citep{Petersen2009}. Therefore, by creating acceleration profiles, FMP, it is now easily accessible for the practitioners to use to monitor player demands in both training and matches. This is especially important for elite football teams who have the means to buy and utilize the collected data, as it assists in the insight of the individual player load. This also makes the data usable during training or matches, which would not be the case for a motion capture analysis approach. 

By using FMP, there is also a potential to create "fingerprints" for different drills. As it is expected that different drills consist of different distributions of the six locomotion categories and can be used to identify drill types. This can potentially assist coaches in planning training routines as they will now have an insight to the loading amplitude of each drill. Though, this requires FMP to be properly validated. Therefore, a part of this study will be allocated to validate the locomotion part (linear or non-linear movement) of the FMP but not the intensity. Intensity will not be validated as there are currently no standard to compare it to. Velocity intensity zones are broadly used but these zones have been arbitrary chosen without any robust theoretical framework behind it \citep{Malone2017}. Furthermore, velocity from GPS data are not euclidean vectors as they do not have a direction, which accelerations from IMUs does. Consequently, if an athlete performs a hard deceleration during a change of direction the velocity would fall to a "low intensity" zone, even though very high amplitude of accelerations are being executed. For linear running locomotion there are also great differences in running technique which affects running economy and performance. Vertical oscillation, range in the transverse rotation, range of horizontal velocity during ground contact and more, are all factors that impacts the running economy \citep{Folland2017} that the GPS can not measure. To validate the locomotion of FMP, different simplified drills can be executed to avoid inter-rater reliability issues \citep{Reinking2018}.


Therefore, the aim of this study was twofold. 1) Validate the locomotion predictions of FMP during controlled and simplified drills. 2) Create an algorithm based on FMP that can predict different drill types. 